version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    # New!
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      linting:
        # A pattern can be...
        patterns:
          - "@commitlint/*" # a single dependency name
          # or a wildcard string that matches multiple dependencies
          # If you'd simply like to group as many dependencies together as possible, 
          # you can use the wildcard * - but keep in mind this may open a very large PR!
        # Additionally, you can specify any dependencies to be excluded from the group
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 30
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 30
