name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: yarn run build

      - run: yarn test
